
-- Native character-phone message network.
-- Run the whole file in Supabase SQL Editor.

create table if not exists public.phone_messages (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  recipient_id text not null,
  body text not null check (char_length(body) between 1 and 1000),
  sent_at timestamptz not null default now()
);

create index if not exists phone_messages_sender_idx
  on public.phone_messages (sender_id, sent_at);

create index if not exists phone_messages_recipient_idx
  on public.phone_messages (recipient_id, sent_at);

alter table public.phone_messages enable row level security;

drop policy if exists "prototype read messages" on public.phone_messages;
create policy "prototype read messages"
on public.phone_messages for select
to anon, authenticated
using (true);

drop policy if exists "prototype send messages" on public.phone_messages;
create policy "prototype send messages"
on public.phone_messages for insert
to anon, authenticated
with check (
  sender_id in ('jace','damian','meggie','juno','aria','kouji','tyler')
  and recipient_id in ('jace','damian','meggie','juno','aria','kouji','tyler')
  and sender_id <> recipient_id
);

drop policy if exists "prototype reset messages" on public.phone_messages;
create policy "prototype reset messages"
on public.phone_messages for delete
to anon, authenticated
using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'phone_messages'
  ) then
    alter publication supabase_realtime add table public.phone_messages;
  end if;
end $$;
